"""Constants used by the CameraReticleExtension"""
import enum


class CompositionGuidelines(enum.IntEnum):
    """Enum representing all of the composition modes."""
    OFF = 0
    THIRDS = 1
    QUAD = 2
    CROSSHAIR = 3


DEFAULT_ACTION_SAFE_COLOR = 0xFF0000FF
DEFAULT_TITLE_SAFE_COLOR = 0xFF00FFFF
DEFAULT_CUSTOM_SAFE_COLOR = 0xFF00FF00
DEFAULT_ACTION_SAFE_PERCENTAGE = 93
DEFAULT_TITLE_SAFE_PERCENTAGE = 90
DEFAULT_CUSTOM_SAFE_PERCENTAGE = 85
DEFAULT_LETTERBOX_COLOR = 0xBB000000
DEFAULT_LETTERBOX_RATIO = 2.35
DEFAULT_COMPOSITION_MODE = CompositionGuidelines.OFF
DEFAULT_COMP_LINES_COLOR = 0x99FFFFFF
